spring:
  profiles:
    active: local

management:
  server:
    ssl:
      enabled: false
  endpoints:
    web:
      exposure:
        include: ['health', 'info', 'metrics', 'prometheus']
  info:
    java:
      enabled: true
    env:
      enabled: true

info:
  app:
    name: Blocking & Reactive Spring Application Demo
